#'''Parameters config.'''#


# --- general --- #

# Choose either 'megahit', 'metaspades', or both
assembler:  'metaspades,megahit' 
# The default is 'meta' (metagenomics DNA) but one of 'rna' (RNA-Seq), 'metaviral' (viral DNA in a metagenomic context), or 'metaplasmid' (plasmid DNA in a metagenomic context) can also be selected
option:     'meta'
