#'''Command-line usage resource config.'''#


count_reads_mem_mb: 100000


# --- general --- #

assembly_threads: 30
assembly_mem_mb:  200000

# --- quast --- #

quast_threads: 30
quast_mem_mb:  200000
